### ISSUE TITLE
"Please log in first to see this page." message instead of redirecting to login screen

### ISSUE THREAD

**Issue by HarmVeenstra** [tslenter/RSX-RSC#35]
When starting browser after system shutdown, the rsc/rsc.php page shows "Please log in first to see this page." It would be nice if, when detecting session is expired, it would redirect automatically to the /rsc page and showing the login prompt

**Comment by tslenter** [comment]
Hi Harm,

We did a quick update for the file: rsc.php. It now automatically redirects back to the rsc login within 10 seconds.

To make a quick update:
mkdir ~/rsc_update
cd ~/rsc_update
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/master/rsc/rsc.php
sudo cp ./rsc.php /var/www/html/rsc/rsc.php

**Comment by HarmVeenstra** [comment]
Great, it now shows:

Please log in first to see this page.

Return to login

And after ten seconds (No counter, doesn't matter) it returns you to the login prompt

**Comment by HarmVeenstra** [comment]
Problem solved by new rsc.php file
