### ISSUE TITLE
var/log/apache2/error.log filling up with session_start messages

### ISSUE THREAD

**Issue by HarmVeenstra** [tslenter/RSX-RSC#42]
[Thu Mar 18 16:57:55.323966 2021] [php7:notice] [pid 1419] [client 192.168.168.153:30183] PHP Notice:  session_start(): A session had already been started - ignoring in /var/www/html/rsc/PHPTail.php on line 33, referer: https://192.168.168.192/rsc/rsc.php

Line 33 is

session_start();
if (isset($_SESSION['id']) && $_SESSION['un'] == true) {
/**
 * Just continue if logged in
 */
} else {
    echo "Please log in first to see this page.";
    exit;
}

Seems to be refreshing/checking and generating errors every few seconds...

**Comment by tslenter** [comment]
Hi Harm,

We did a quick update for the file: PHPTail.php within the development code. The flooding of the message should be gone by updating this file.

To make a quick update:
mkdir ~/rsc_update
cd ~/rsc_update
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/development/rsc/PHPTail.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php

Rollback:
mkdir ~/rsc_rollback
cd ~/rsc_rollback
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/master/rsc/PHPTail.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php

**Comment by HarmVeenstra** [comment]
The error message is no longer logged, but this one now logged

[Fri Mar 19 10:05:00.911239 2021] [php7:notice] [pid 17990] [client 192.168.168.153:19580] PHP Notice:  Undefined index: pg in /var/www/html/rsc/PHPTail.php on line 367, referer: https://192.168.168.192/rsc/index.php

line 367 <li <?php if ($_GET['pg'] == "ar") { exec('rm -rf /var/log/remote_syslog/remote_syslog.log.*'); } ?>><a href="?pg=ar">Clear live log archive</a></li>

**Comment by tslenter** [comment]
Hi Harm,

We did a quick update for the file: PHPTail.php and rscforwarder.php within the development code. The variable/index messages should be gone.

To make a quick update:
mkdir ~/rsc_update
cd ~/rsc_update
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/development/rsc/PHPTail.php
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/development/rsc/rscforwarder.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php
sudo cp ./rscforwarder.php /var/www/html/index.php

Rollback:
mkdir ~/rsc_rollback
cd ~/rsc_rollback
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/master/rsc/PHPTail.php
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/master/rsc/rscforwarder.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php
sudo cp ./rscforwarder.php /var/www/html/index.php

**Comment by HarmVeenstra** [comment]
Thanks, errors are gone now!

**Comment by tslenter** [comment]
Hi Harm,

Thanks for letting us know that the solution fixed the issue. We pushed this fix to the master branch.
